source "https://rubygems.org"

gem "rspec", "3.10"
gem "httparty", "0.18.1"
gem "mongo", "2.13.1"
gem "rspec_junit_formatter", "~> 0.4.1"
gem "dotenv", "~> 2.8", ">= 2.8.1"
gem "yaml", "~> 0.2.1"
